# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcp_bridge.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tcp_bridge.proto\x12\x0crobot_bridge\"q\n\tSimConfig\x12\x12\n\nscene_path\x18\x01 \x01(\t\x12\n\n\x02\x64t\x18\x02 \x01(\x01\x12\x13\n\x0bjoint_names\x18\x03 \x03(\t\x12/\n\ninit_state\x18\x04 \x01(\x0b\x32\x1b.robot_bridge.RobotStateMsg\"\xcb\x01\n\rRobotStateMsg\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x15\n\rroot_position\x18\x02 \x03(\x01\x12\x18\n\x10root_orientation\x18\x03 \x03(\x01\x12\x17\n\x0froot_linear_vel\x18\x04 \x03(\x01\x12\x18\n\x10root_angular_vel\x18\x05 \x03(\x01\x12\x17\n\x0fjoint_positions\x18\x06 \x03(\x01\x12\x18\n\x10joint_velocities\x18\x07 \x03(\x01\x12\x15\n\rcontact_flags\x18\x08 \x03(\x08\"d\n\x0eJointActionMsg\x12\r\n\x05q_des\x18\x01 \x03(\x01\x12\x0e\n\x06qd_des\x18\x02 \x03(\x01\x12\n\n\x02kp\x18\x03 \x03(\x01\x12\n\n\x02kd\x18\x04 \x03(\x01\x12\x1b\n\x13\x66\x65\x65\x64_forward_effort\x18\x05 \x03(\x01\"\xd9\x01\n\nTcpMessage\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.robot_bridge.MessageType\x12-\n\nsim_config\x18\x02 \x01(\x0b\x32\x17.robot_bridge.SimConfigH\x00\x12\x32\n\x0brobot_state\x18\x03 \x01(\x0b\x32\x1b.robot_bridge.RobotStateMsgH\x00\x12\x34\n\x0cjoint_action\x18\x04 \x01(\x0b\x32\x1c.robot_bridge.JointActionMsgH\x00\x42\t\n\x07payload*\x83\x01\n\x0bMessageType\x12\x0f\n\x0bINIT_CONFIG\x10\x00\x12\x0c\n\x08INIT_SIM\x10\x01\x12\r\n\tSTART_SIM\x10\x02\x12\r\n\tGET_STATE\x10\x03\x12\x0f\n\x0bSEND_ACTION\x10\x04\x12\t\n\x05RESET\x10\x05\x12\x12\n\x0eSTATE_RESPONSE\x10\x06\x12\x07\n\x03\x41\x43K\x10\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tcp_bridge_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=678
  _MESSAGETYPE._serialized_end=809
  _SIMCONFIG._serialized_start=34
  _SIMCONFIG._serialized_end=147
  _ROBOTSTATEMSG._serialized_start=150
  _ROBOTSTATEMSG._serialized_end=353
  _JOINTACTIONMSG._serialized_start=355
  _JOINTACTIONMSG._serialized_end=455
  _TCPMESSAGE._serialized_start=458
  _TCPMESSAGE._serialized_end=675
# @@protoc_insertion_point(module_scope)
