<?xml version="1.0"?>
<package format="3">
  <name>humanoid_stylized_mpc_ros2</name>
  <version>0.1.0</version>
  <description>ROS2 node and glue for the stylized whole-body humanoid MPC</description>
  <maintainer email="dxa239@nyu.edu">Daniel</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>humanoid_stylized_mpc</depend>
  <depend>humanoid_stylized_mpc_msgs</depend>
  <depend>humanoid_common_mpc</depend>
  <depend>humanoid_wb_mpc</depend>
  <depend>ocs2_ros2_interfaces</depend>
  <depend>ocs2_sqp</depend>

  <exec_depend>humanoid_wb_mpc_ros2</exec_depend>
  <exec_depend>g1_wb_mpc</exec_depend>
  <exec_depend>g1_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
